// package/react/esm/components/Message.js
function _extends() { _extends = Object.assign ? Object.assign.bind() : function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; }; return _extends.apply(this, arguments); }
/* eslint-disable jsx-a11y/alt-text */
import React, { useRef,
// useState,
forwardRef, useImperativeHandle } from 'react';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import { cls } from '../../../shared/esm/cls.js';
// import { useTheme } from '../shared/use-theme.js';
import { useDarkClasses } from '../shared/use-dark-classes.js';
import { MessageClasses } from '../../../shared/esm/classes/MessageClasses.js';
import { MessageColors } from '../../../shared/esm/colors/MessageColors.js';
const Message = /*#__PURE__*/forwardRef((props, ref) => {
  const {
    component = 'div',
    className,
    colors: colorsProp,
    id,
    text,
    name,
    type = 'sent',
    header,
    footer,
    textHeader,
    textFooter,
    avatar,
    ios,
    material,
    children,
    ...rest
  } = props;
  const elRef = useRef(null);
  useImperativeHandle(ref, () => ({
    el: elRef.current
  }));
  // const theme = useTheme({ ios, material });
  const themeClasses = useThemeClasses({
    ios,
    material
  });
  const dark = useDarkClasses();
  const colors = MessageColors(colorsProp, dark);
  const c = themeClasses(MessageClasses({
    ...props
  }, colors));
  const Component = component;
  const attrs = {
    ...rest
  };
  const classes = cls(className, c.message, {
    [c.messageSent]: type === 'sent',
    [c.messageReceived]: type === 'received'
  });
  return /*#__PURE__*/React.createElement(Component, _extends({
    id: id,
    ref: elRef,
    className: classes
  }, attrs), avatar && /*#__PURE__*/React.createElement("div", {
    className: c.messageAvatar
  }, avatar), /*#__PURE__*/React.createElement("div", {
    className: c.messageContent
  }, name && /*#__PURE__*/React.createElement("div", {
    className: c.messageName
  }, name), header && /*#__PURE__*/React.createElement("div", {
    className: c.messageHeader
  }, header), /*#__PURE__*/React.createElement("div", {
    className: c.messageBubble
  }, textHeader && /*#__PURE__*/React.createElement("div", {
    className: c.messageTextHeader
  }, textHeader), text && /*#__PURE__*/React.createElement("div", {
    className: c.messageText
  }, text), textFooter && /*#__PURE__*/React.createElement("div", {
    className: c.messageTextFooter
  }, textFooter)), footer && /*#__PURE__*/React.createElement("div", {
    className: c.messageFooter
  }, footer)));
});
Message.displayName = 'Message';
export default Message;

// package/vue/components/Message.vue
<template>
  <component :is="component" :id="id" ref="elRef" :class="classes">
    <div v-if="avatar || $slots.avatar" :class="c.messageAvatar">
      {{ avatar }}<slot name="avatar" />
    </div>
    <div :class="c.messageContent">
      <div v-if="name || $slots.name" :class="c.messageName">
        {{ name }}<slot name="name" />
      </div>
      <div v-if="header || $slots.header" :class="c.messageHeader">
        {{ header }}<slot name="header" />
      </div>
      <div :class="c.messageBubble">
        <div
          v-if="textHeader || $slots.textHeader"
          :class="c.messageTextHeader"
        >
          {{ textHeader }}<slot name="textHeader" />
        </div>
        <div v-if="text || $slots.text" :class="c.messageText">
          {{ text }}<slot name="text" />
        </div>
        <div
          v-if="textFooter || $slots.textFooter"
          :class="c.messageTextFooter"
        >
          {{ textFooter }}<slot name="textFooter" />
        </div>
        <div v-if="footer || $slots.footer" :class="c.messageFooter">
          {{ footer }}<slot name="footer" />
        </div>
      </div>
    </div>
  </component>
</template>
<script>
  import { ref, computed } from 'vue';
  import { cls } from '../../shared/esm/cls.js';
  import { MessageClasses } from '../../shared/esm/classes/MessageClasses.js';
  import { MessageColors } from '../../shared/esm/colors/MessageColors.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  export default {
    name: 'k-message',
    props: {
      component: {
        type: String,
        default: 'div',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      id: String,
      text: String,
      name: String,
      type: { type: String, default: 'sent' },
      header: String,
      footer: String,
      textHeader: String,
      textFooter: String,
      avatar: { type: String, default: null },
    },
    setup(props, ctx) {
      const elRef = ref(null);

      const colors = computed(() =>
        MessageColors(props.colors || {}, useDarkClasses)
      );

      const c = useThemeClasses(props, () =>
        MessageClasses({ ...props }, colors.value)
      );

      const classes = computed(() =>
        cls(
          c.value.message,
          props.type === 'sent' && c.value.messageSent,
          props.type === 'received' && c.value.messageReceived
        )
      );
      return {
        c,
        classes,
        elRef,
        slots: ctx.slots,
      };
    },
  };
</script>
