// package/react/esm/components/TabbarLink.js
function _extends() { _extends = Object.assign ? Object.assign.bind() : function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; }; return _extends.apply(this, arguments); }
import React, { useRef, forwardRef, useImperativeHandle } from 'react';
import { TabbarLinkClasses } from '../../../shared/esm/classes/TabbarLinkClasses.js';
import { TabbarLinkColors } from '../../../shared/esm/colors/TabbarLinkColors.js';
import { useDarkClasses } from '../shared/use-dark-classes.js';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import Link from './Link.js';
const TabbarLink = /*#__PURE__*/forwardRef((props, ref) => {
  const {
    className,
    active,
    ios,
    material,
    colors: colorsProp,
    linkProps = {},
    icon,
    label,
    children,
    ...rest
  } = props;
  const elRef = useRef(null);
  useImperativeHandle(ref, () => ({
    el: elRef.current
  }));
  const attrs = {
    ...linkProps,
    ...rest
  };
  const dark = useDarkClasses();
  const colors = TabbarLinkColors(colorsProp, dark);
  const themeClasses = useThemeClasses({
    ios,
    material
  });
  const hasIcon = !!icon;
  const hasLabel = label || children && children.length;
  const c = themeClasses(TabbarLinkClasses({
    hasLabel,
    hasIcon,
    active
  }, colors));
  return /*#__PURE__*/React.createElement(Link, _extends({
    ref: elRef,
    tabbar: true,
    tabbarActive: active,
    className: className
  }, attrs), /*#__PURE__*/React.createElement("span", {
    className: c.content
  }, icon && /*#__PURE__*/React.createElement("span", {
    className: c.iconContainer
  }, /*#__PURE__*/React.createElement("span", {
    className: c.iconBg
  }), icon), (label || children && children.length) && /*#__PURE__*/React.createElement("span", {
    className: c.label
  }, label, children)));
});
TabbarLink.displayName = 'TabbarLink';
export default TabbarLink;

// package/vue/components/TabbarLink.vue
<template>
  <k-link
    tabbar
    :tabbar-active="active"
    :component="component"
    :colors="colors"
    :touch-ripple="touchRipple"
    v-bind="linkProps"
  >
    <span :class="c.content">
      <template v-if="slots.icon">
        <span :class="c.iconContainer">
          <span :class="c.iconBg" />
          <slot name="icon" />
        </span>
      </template>
      <template v-if="label || slots.label || slots.default">
        <span :class="c.label">
          {{ label }}
          <slot name="label" />
          <slot />
        </span>
      </template>
    </span>
  </k-link>
</template>
<script>
  import { computed, ref, onBeforeUpdate } from 'vue';
  import { TabbarLinkClasses } from '../../shared/esm/classes/TabbarLinkClasses.js';
  import { TabbarLinkColors } from '../../shared/esm/colors/TabbarLinkColors.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import kLink from './Link.vue';

  export default {
    name: 'k-tabbar-link',
    components: {
      kLink,
    },
    props: {
      component: {
        type: String,
        default: 'a',
      },
      colors: {
        type: Object,
      },
      touchRipple: { type: Boolean, default: true },
      linkProps: { type: Object, default: () => ({}) },
      active: {
        type: Boolean,
        default: false,
      },
      label: { type: String, default: undefined },
    },
    setup(props, ctx) {
      const colors = computed(() =>
        TabbarLinkColors(props.colors, useDarkClasses)
      );
      const hasIcon = ref(ctx.slots.icon);
      const hasLabel = ref(props.label || ctx.slots.label || ctx.slots.default);
      const c = useThemeClasses(props, () =>
        TabbarLinkClasses(
          {
            active: props.active,
            hasIcon: hasIcon.value,
            hasLabel: hasLabel.value,
          },
          colors.value
        )
      );
      onBeforeUpdate(() => {
        hasIcon.value = ctx.slots.icon;
        hasLabel.value = props.label || ctx.slots.label || ctx.slots.default;
      });
      return {
        c,
        slots: ctx.slots,
      };
    },
  };
</script>
