// package/react/esm/components/TableRow.js
function _extends() { _extends = Object.assign ? Object.assign.bind() : function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; }; return _extends.apply(this, arguments); }
import React, { useRef, forwardRef, useImperativeHandle } from 'react';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import { useDarkClasses } from '../shared/use-dark-classes.js';
import { TableRowClasses } from '../../../shared/esm/classes/TableRowClasses.js';
import { TableRowColors } from '../../../shared/esm/colors/TableRowColors.js';
const TableRow = /*#__PURE__*/forwardRef((props, ref) => {
  const {
    className,
    colors: colorsProp,
    header,
    ios,
    material,
    children,
    ...rest
  } = props;
  const elRef = useRef(null);
  useImperativeHandle(ref, () => ({
    el: elRef.current
  }));
  const themeClasses = useThemeClasses({
    ios,
    material
  });
  const dark = useDarkClasses();
  const colors = TableRowColors(colorsProp, dark);
  const c = themeClasses(TableRowClasses({
    ...props
  }, colors));
  const attrs = {
    ...rest
  };
  return /*#__PURE__*/React.createElement("tr", _extends({
    className: c.base,
    ref: elRef
  }, attrs), children);
});
TableRow.displayName = 'TableRow';
export default TableRow;

// package/vue/components/TableRow.vue
<template>
  <tr ref="elRef" :class="c.base">
    <slot />
  </tr>
</template>
<script>
  import { ref, computed } from 'vue';
  import { TableRowClasses } from '../../shared/esm/classes/TableRowClasses.js';
  import { TableRowColors } from '../../shared/esm/colors/TableRowColors.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';

  export default {
    name: 'k-table-row',
    props: {
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      header: {
        type: Boolean,
        default: false,
      },
    },
    setup(props, ctx) {
      const elRef = ref(null);

      const colors = computed(() =>
        TableRowColors(props.colors || {}, useDarkClasses)
      );
      const c = useThemeClasses(props, () =>
        TableRowClasses(props, colors.value, ctx.attrs.class)
      );

      return {
        c,
        elRef,
      };
    },
  };
</script>
