// package/vue/components/Button.vue
<template>
  <component
    :is="Component"
    ref="rippleElRef"
    :class="classes"
    :disabled="disabled"
    role="button"
    tabindex="0"
  >
    <slot />
  </component>
</template>
<script>
  import { ref, computed } from 'vue';
  import { cls } from '../../shared/esm/cls.js';
  import { useTouchRipple } from '../shared/use-touch-ripple.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useTheme } from '../shared/use-theme.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { ButtonClasses } from '../../shared/esm/classes/ButtonClasses.js';
  import { ButtonColors } from '../../shared/esm/colors/ButtonColors.js';

  export default {
    name: 'k-button',
    props: {
      component: {
        type: String,
        default: 'button',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      // Anchor props
      href: {
        type: [Boolean, String],
        default: undefined,
      },

      // Style props
      outline: {
        type: Boolean,
        default: undefined,
      },
      outlineIos: {
        type: Boolean,
        default: undefined,
      },
      outlineMaterial: {
        type: Boolean,
        default: undefined,
      },
      clear: {
        type: Boolean,
        default: undefined,
      },
      clearIos: {
        type: Boolean,
        default: undefined,
      },
      clearMaterial: {
        type: Boolean,
        default: undefined,
      },
      tonal: {
        type: Boolean,
        default: undefined,
      },
      tonalIos: {
        type: Boolean,
        default: undefined,
      },
      tonalMaterial: {
        type: Boolean,
        default: undefined,
      },
      rounded: {
        type: Boolean,
        default: undefined,
      },
      roundedIos: {
        type: Boolean,
        default: undefined,
      },
      roundedMaterial: {
        type: Boolean,
        default: undefined,
      },
      small: {
        type: Boolean,
        default: undefined,
      },
      smallIos: {
        type: Boolean,
        default: undefined,
      },
      smallMaterial: {
        type: Boolean,
        default: undefined,
      },
      large: {
        type: Boolean,
        default: undefined,
      },
      largeIos: {
        type: Boolean,
        default: undefined,
      },
      largeMaterial: {
        type: Boolean,
        default: undefined,
      },
      raised: {
        type: Boolean,
        default: undefined,
      },
      raisedIos: {
        type: Boolean,
        default: undefined,
      },
      raisedMaterial: {
        type: Boolean,
        default: undefined,
      },

      inline: {
        type: Boolean,
        default: false,
      },

      // Segmented
      segmented: {
        type: Boolean,
        default: false,
      },
      segmentedStrong: {
        type: Boolean,
        default: false,
      },
      segmentedActive: {
        type: Boolean,
        default: false,
      },

      touchRipple: {
        type: Boolean,
        default: true,
      },

      disabled: {
        type: Boolean,
        default: false,
      },
    },
    setup(props, ctx) {
      const rippleElRef = ref(null);
      const Component = computed(() => {
        let c = props.component;
        if (
          typeof props.component === 'undefined' &&
          (props.href || props.href === '')
        ) {
          c = 'a';
        }
        return c;
      });

      useTouchRipple(rippleElRef, props);

      const theme = useTheme();

      const isOutline = computed(() =>
        typeof props.outline === 'undefined'
          ? theme.value === 'ios'
            ? props.outlineIos
            : props.outlineMaterial
          : props.outline
      );
      const isClear = computed(() =>
        typeof props.clear === 'undefined'
          ? theme.value === 'ios'
            ? props.clearIos
            : props.clearMaterial
          : props.clear
      );
      const isTonal = computed(() =>
        typeof props.tonal === 'undefined'
          ? theme.value === 'ios'
            ? props.tonalIos
            : props.tonalMaterial
          : props.tonal
      );
      const isRounded = computed(() =>
        typeof props.rounded === 'undefined'
          ? theme.value === 'ios'
            ? props.roundedIos
            : props.roundedMaterial
          : props.rounded
      );
      const isSmall = computed(() =>
        typeof props.small === 'undefined'
          ? theme.value === 'ios'
            ? props.smallIos
            : props.smallMaterial
          : props.small
      );
      const isLarge = computed(() =>
        typeof props.large === 'undefined'
          ? theme.value === 'ios'
            ? props.largeIos
            : props.largeMaterial
          : props.large
      );
      const isRaised = computed(() =>
        typeof props.raised === 'undefined'
          ? theme.value === 'ios'
            ? props.raisedIos
            : props.raisedMaterial
          : props.raised
      );

      const size = computed(() =>
        isLarge.value ? 'large' : isSmall.value ? 'small' : 'medium'
      );
      const style = computed(() => {
        let value = isOutline.value
          ? 'outline'
          : isClear.value || (props.segmented && !props.segmentedActive)
          ? 'clear'
          : isTonal.value
          ? 'tonal'
          : 'fill';
        if (props.segmentedStrong) value = 'segmentedStrong';
        if (props.segmentedStrong && props.segmentedActive)
          value = 'segmentedStrongActive';
        return value;
      });
      const colors = computed(() =>
        ButtonColors(props.colors || {}, useDarkClasses)
      );

      const c = useThemeClasses(props, () =>
        ButtonClasses(
          {
            ...props,
            outline: isOutline.value,
            clear: isClear.value,
            tonal: isTonal.value,
            rounded: isRounded.value,
            small: isSmall.value,
            large: isLarge.value,
            raised: isRaised.value,
          },
          colors.value,
          ctx.attrs.class,
          useDarkClasses
        )
      );

      const classes = computed(() =>
        cls(
          c.value.base[isRounded.value ? 'rounded' : 'square'],

          // style
          c.value.style[style.value],

          // size
          c.value.size[size.value],

          isRaised.value && c.value.raised
        )
      );

      return {
        rippleElRef,
        classes,
        Component,
      };
    },
  };
</script>

// package/react/cjs/components/Button.js
"use strict";

exports.__esModule = true;
exports.default = void 0;
var _react = _interopRequireWildcard(require("react"));
var _cls = require("../../../shared/cjs/cls.js");
var _useTheme = require("../shared/use-theme.js");
var _useTouchRipple = require("../shared/use-touch-ripple.js");
var _useThemeClasses = require("../shared/use-theme-classes.js");
var _useDarkClasses = require("../shared/use-dark-classes.js");
var _ButtonClasses = require("../../../shared/cjs/classes/ButtonClasses.js");
var _ButtonColors = require("../../../shared/cjs/colors/ButtonColors.js");
function _getRequireWildcardCache(e) { if ("function" != typeof WeakMap) return null; var r = new WeakMap(), t = new WeakMap(); return (_getRequireWildcardCache = function (e) { return e ? t : r; })(e); }
function _interopRequireWildcard(e, r) { if (!r && e && e.__esModule) return e; if (null === e || "object" != typeof e && "function" != typeof e) return { default: e }; var t = _getRequireWildcardCache(r); if (t && t.has(e)) return t.get(e); var n = { __proto__: null }, a = Object.defineProperty && Object.getOwnPropertyDescriptor; for (var u in e) if ("default" !== u && Object.prototype.hasOwnProperty.call(e, u)) { var i = a ? Object.getOwnPropertyDescriptor(e, u) : null; i && (i.get || i.set) ? Object.defineProperty(n, u, i) : n[u] = e[u]; } return n.default = e, t && t.set(e, n), n; }
function _extends() { _extends = Object.assign ? Object.assign.bind() : function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; }; return _extends.apply(this, arguments); }
const Button = /*#__PURE__*/(0, _react.forwardRef)((props, ref) => {
  const {
    component = 'button',
    className,
    colors: colorsProp,
    ios,
    material,
    disabled,
    // Anchor props
    href,
    // Style props
    outline,
    outlineIos,
    outlineMaterial,
    clear,
    clearIos,
    clearMaterial,
    tonal,
    tonalIos,
    tonalMaterial,
    rounded,
    roundedIos,
    roundedMaterial,
    small,
    smallIos,
    smallMaterial,
    large,
    largeIos,
    largeMaterial,
    raised,
    raisedIos,
    raisedMaterial,
    inline,
    // Segmented
    segmented,
    segmentedStrong,
    segmentedActive,
    touchRipple = true,
    // Children
    children,
    // Rest
    ...rest
  } = props;
  const rippleElRef = (0, _react.useRef)(null);
  (0, _react.useImperativeHandle)(ref, () => ({
    el: rippleElRef.current
  }));
  let Component = component;
  if (typeof props.component === 'undefined' && (href || href === '')) Component = 'a';
  const attrs = {
    href,
    ...rest
  };
  const theme = (0, _useTheme.useTheme)({
    ios,
    material
  });
  const themeClasses = (0, _useThemeClasses.useThemeClasses)({
    ios,
    material
  });
  const dark = (0, _useDarkClasses.useDarkClasses)();
  (0, _useTouchRipple.useTouchRipple)(rippleElRef, theme === 'material' && touchRipple);
  const getThemeSpecificProps = obj => {
    const res = {};
    Object.keys(obj).forEach(key => {
      res[key] = typeof obj[key] === 'undefined' ? theme === 'ios' ? props[`${key}Ios`] : props[`${key}Material`] : obj[key];
    });
    return res;
  };
  const themeProps = getThemeSpecificProps({
    outline,
    clear,
    tonal,
    rounded,
    small,
    large,
    raised
  });
  const size = themeProps.large ? 'large' : themeProps.small ? 'small' : 'medium';
  let style = themeProps.outline ? 'outline' : themeProps.clear || segmented && !segmentedActive ? 'clear' : themeProps.tonal ? 'tonal' : 'fill';
  if (segmentedStrong) style = 'segmentedStrong';
  if (segmentedStrong && segmentedActive) style = 'segmentedStrongActive';
  const colors = (0, _ButtonColors.ButtonColors)(colorsProp, dark);
  const c = themeClasses((0, _ButtonClasses.ButtonClasses)({
    ...props,
    ...themeProps
  }, colors, className, dark));
  const classes = (0, _cls.cls)(c.base[themeProps.rounded ? 'rounded' : 'square'],
  // style
  c.style[style],
  // size
  c.size[size], themeProps.raised && c.raised, className);
  return /*#__PURE__*/_react.default.createElement(Component, _extends({
    ref: rippleElRef,
    className: classes,
    disabled: disabled,
    role: "button",
    tabIndex: "0"
  }, attrs), children);
});
Button.displayName = 'Button';
var _default = exports.default = Button;
