// package/vue/components/ListItem.vue
<template>
  <component :is="component" v-if="groupTitle" :class="c.groupTitle">
    {{ title }}
    <slot name="title" />
    <slot />
  </component>
  <component :is="component" v-else :class="c.base">
    <component
      :is="ItemContentComponent"
      ref="rippleElRef"
      :class="itemContentClasses"
      v-bind="linkPropsComputed"
    >
      <div v-if="media || slots.media" :class="c.media">
        {{ media }}<slot name="media" />
      </div>
      <div :class="c.inner">
        <div v-if="header || slots.header" :class="c.header">
          {{ header }}<slot name="header" />
        </div>
        <div
          v-if="title || after || slots.title || slots.after"
          :class="c.titleWrap"
        >
          <div v-if="title || slots.title" :class="titleClasses">
            {{ title }}<slot name="title" />
          </div>
          <div v-if="after || slots.after" :class="c.after">
            {{ after }}<slot name="after" />
          </div>
          <chevron-icon
            v-if="isLink && hasChevron && !menuListItem"
            :class="c.chevron"
          />
        </div>
        <div v-if="subtitle || slots.subtitle" :class="c.subtitle">
          {{ subtitle }}<slot name="subtitle" />
        </div>
        <div v-if="text || slots.text" :class="c.text">
          {{ text }}<slot name="text" />
        </div>
        <div v-if="footer || slots.footer" :class="c.footer">
          {{ footer }}<slot name="footer" />
        </div>
        <slot name="inner" />
      </div>
      <slot name="content" />
    </component>
    <slot />
  </component>
</template>
<script>
  import { ref, computed, inject } from 'vue';
  import { useTheme } from '../shared/use-theme.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useTouchRipple } from '../shared/use-touch-ripple.js';
  import ChevronIcon from './icons/ChevronIcon.vue';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { ListItemClasses } from '../../shared/esm/classes/ListItemClasses.js';
  import { ListItemColors } from '../../shared/esm/colors/ListItemColors.js';

  export default {
    name: 'k-list-item',
    components: {
      ChevronIcon,
    },
    props: {
      component: {
        type: String,
        default: 'li',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      mediaClass: { type: String, default: '' },
      innerClass: { type: String, default: '' },
      contentClass: { type: String, default: '' },
      titleWrapClass: { type: String, default: '' },
      titleFontSizeIos: { type: String, default: 'text-[17px]' },
      titleFontSizeMaterial: {
        type: String,
        default: 'text-[16px]',
      },

      dividers: {
        type: Boolean,
        default: undefined,
      },
      contacts: {
        type: Boolean,
        default: undefined,
      },

      // Content props
      title: { type: String, default: undefined },
      subtitle: { type: String, default: undefined },
      text: { type: String, default: undefined },
      after: { type: String, default: undefined },
      media: { type: String, default: undefined },
      header: { type: String, default: undefined },
      footer: { type: String, default: undefined },

      menuListItem: { type: Boolean, default: false },
      menuListItemActive: { type: Boolean, default: false },

      groupTitle: { type: Boolean, default: false },

      // Title
      strongTitle: { type: [String, Boolean], default: 'auto' },

      // Label props
      label: { type: Boolean, default: false },

      // Link props
      chevron: { type: Boolean, default: undefined },
      chevronIos: { type: Boolean, default: true },
      chevronMaterial: { type: Boolean, default: true },
      href: { type: [Boolean, String], default: undefined },
      target: { type: String, default: undefined },

      link: { type: Boolean, default: undefined },
      linkComponent: { type: String, default: 'a' },
      linkProps: { type: Object, default: () => ({}) },

      touchRipple: { type: Boolean, default: true },
    },
    setup(props, ctx) {
      const rippleElRef = ref(null);
      const theme = useTheme(props);

      const colors = computed(() =>
        ListItemColors(props.colors || {}, useDarkClasses)
      );

      const isMenuListItemActive = computed(
        () => props.menuListItem && props.menuListItemActive
      );

      const hasChevron = computed(() =>
        typeof props.chevron === 'undefined'
          ? theme.value === 'ios'
            ? props.chevronIos
            : props.chevronMaterial
          : props.chevron
      );

      const textColor = computed(
        () =>
          colors.value[
            `${
              isMenuListItemActive.value
                ? 'menuListItemActiveText'
                : props.menuListItem
                ? 'menuListItemText'
                : 'text'
            }${theme.value === 'ios' ? 'Ios' : 'Material'}`
          ]
      );

      const isLink = computed(
        () =>
          !!props.href || props.href === '' || props.menuListItem || props.link
      );
      const isLabel = computed(() => !!props.label);

      const needsTouchRipple = computed(
        () =>
          theme.value === 'material' &&
          (isLabel.value || isLink.value) &&
          props.touchRipple
      );
      useTouchRipple(rippleElRef, props, {
        addCondition: () => isLabel.value || isLink.value,
      });

      const hrefComputed = computed(() =>
        props.href === true ||
        props.href === false ||
        typeof props.href === 'undefined'
          ? undefined
          : props.href || ''
      );
      const ItemContentComponent = computed(() =>
        isLink.value ? props.linkComponent : isLabel.value ? 'label' : 'div'
      );
      const linkPropsComputed = computed(() =>
        isLink.value
          ? {
              href: hrefComputed.value,
              target: props.target,
              ...(props.linkProps || {}),
            }
          : {}
      );

      const isMediaItem = computed(
        () =>
          (props.title || ctx.slots.title) &&
          (props.subtitle || ctx.slots.subtitle || props.text || ctx.slots.text)
      );

      const autoStrongTitle = computed(
        () => props.strongTitle === 'auto' && isMediaItem.value
      );

      const ListDividersContext = inject('ListDividersContext', {
        value: false,
      });

      const c = useThemeClasses(props, () =>
        ListItemClasses(
          {
            ...props,
            dividers:
              typeof props.dividers === 'undefined'
                ? ListDividersContext.value
                : props.dividers,
            contacts:
              typeof props.contacts === 'undefined' ? '' : props.contacts,
          },
          colors.value,
          {
            isMediaItem: isMediaItem.value,
            theme: theme.value,
            textColor: textColor.value,
            needsTouchRipple: needsTouchRipple.value,
            isMenuListItemActive: isMenuListItemActive.value,
            darkClasses: useDarkClasses,
            autoStrongTitle: autoStrongTitle.value,
            className: ctx.attrs.class,
          }
        )
      );

      const itemContentClasses = computed(() =>
        isLink.value || isLabel.value
          ? c.value.itemContent.link
          : c.value.itemContent.default
      );

      const titleClasses = computed(() =>
        props.menuListItem
          ? c.value.title.menuListItem
          : props.strongTitle === true || autoStrongTitle.value
          ? c.value.title.strong
          : c.value.title.default
      );

      return {
        rippleElRef,
        ItemContentComponent,
        isLink,
        c,
        hasChevron,
        linkPropsComputed,
        itemContentClasses,
        titleClasses,
        slots: ctx.slots,
      };
    },
  };
</script>

// package/react/cjs/components/ListItem.js
"use strict";

exports.__esModule = true;
exports.default = void 0;
var _react = _interopRequireWildcard(require("react"));
var _cls = require("../../../shared/cjs/cls.js");
var _useTheme = require("../shared/use-theme.js");
var _useThemeClasses = require("../shared/use-theme-classes.js");
var _useTouchRipple = require("../shared/use-touch-ripple.js");
var _ChevronIcon = _interopRequireDefault(require("./icons/ChevronIcon.js"));
var _useDarkClasses = require("../shared/use-dark-classes.js");
var _ListItemClasses = require("../../../shared/cjs/classes/ListItemClasses.js");
var _ListItemColors = require("../../../shared/cjs/colors/ListItemColors.js");
var _useListDividers = require("../shared/use-list-dividers.js");
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
function _getRequireWildcardCache(e) { if ("function" != typeof WeakMap) return null; var r = new WeakMap(), t = new WeakMap(); return (_getRequireWildcardCache = function (e) { return e ? t : r; })(e); }
function _interopRequireWildcard(e, r) { if (!r && e && e.__esModule) return e; if (null === e || "object" != typeof e && "function" != typeof e) return { default: e }; var t = _getRequireWildcardCache(r); if (t && t.has(e)) return t.get(e); var n = { __proto__: null }, a = Object.defineProperty && Object.getOwnPropertyDescriptor; for (var u in e) if ("default" !== u && Object.prototype.hasOwnProperty.call(e, u)) { var i = a ? Object.getOwnPropertyDescriptor(e, u) : null; i && (i.get || i.set) ? Object.defineProperty(n, u, i) : n[u] = e[u]; } return n.default = e, t && t.set(e, n), n; }
function _extends() { _extends = Object.assign ? Object.assign.bind() : function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; }; return _extends.apply(this, arguments); }
const ListItem = /*#__PURE__*/(0, _react.forwardRef)((props, ref) => {
  const {
    component = 'li',
    colors: colorsProp,
    className,
    mediaClassName = '',
    innerClassName = '',
    innerChildren,
    contentClassName = '',
    contentChildren,
    titleWrapClassName = '',
    titleFontSizeIos = 'text-[17px]',
    titleFontSizeMaterial = 'text-[16px]',
    // Content props
    title,
    subtitle,
    text,
    after,
    media,
    header,
    footer,
    menuListItem,
    menuListItemActive,
    groupTitle,
    // Title
    strongTitle = 'auto',
    // Label props
    label,
    // Link props
    chevron = undefined,
    chevronIos = true,
    chevronMaterial = true,
    chevronIcon,
    href,
    target,
    link,
    linkComponent = 'a',
    linkProps = {},
    dividers: dividersProp,
    contacts,
    ios,
    material,
    touchRipple = true,
    // Children
    children,
    // Rest
    ...rest
  } = props;
  const rippleElRef = (0, _react.useRef)(null);
  const elRef = (0, _react.useRef)(null);
  (0, _react.useImperativeHandle)(ref, () => ({
    el: elRef.current
  }));
  const Component = component;
  const attrs = {
    ...rest
  };
  const dividers = typeof dividersProp === 'undefined' ? (0, _useListDividers.useListDividers)() : dividersProp;
  const theme = (0, _useTheme.useTheme)({
    ios,
    material
  });
  const themeClasses = (0, _useThemeClasses.useThemeClasses)({
    ios,
    material
  });
  const dark = (0, _useDarkClasses.useDarkClasses)();
  const hasChevron = typeof chevron === 'undefined' ? theme === 'ios' ? chevronIos : chevronMaterial : chevron;
  const colors = (0, _ListItemColors.ListItemColors)(colorsProp, dark);
  const isMenuListItemActive = menuListItem && menuListItemActive;
  const textColor = colors[`${isMenuListItemActive ? 'menuListItemActiveText' : menuListItem ? 'menuListItemText' : 'text'}${theme === 'ios' ? 'Ios' : 'Material'}`];
  const isLink = !!href || href === '' || menuListItem || link;
  const isLabel = !!label;
  const needsTouchRipple = theme === 'material' && (isLabel || isLink) && touchRipple;
  (0, _useTouchRipple.useTouchRipple)(rippleElRef, needsTouchRipple);
  const hrefComputed = href === true || href === false || typeof href === 'undefined' ? undefined : href || '';
  const ItemContentComponent = isLink ? linkComponent : isLabel ? 'label' : 'div';
  const linkPropsComputed = isLink ? {
    href: hrefComputed,
    target,
    ...linkProps
  } : {};
  const isMediaItem = title && (subtitle || text);
  const autoStrongTitle = strongTitle === 'auto' && isMediaItem;
  const c = themeClasses((0, _ListItemClasses.ListItemClasses)({
    ...props,
    titleFontSizeIos,
    titleFontSizeMaterial,
    dividers,
    strongTitle,
    mediaClassName,
    innerClassName,
    contentClassName,
    titleWrapClassName
  }, colors, {
    isMediaItem,
    theme,
    textColor,
    needsTouchRipple,
    isMenuListItemActive,
    darkClasses: dark,
    autoStrongTitle,
    className
  }), className);
  const itemContentClasses = isLink || isLabel ? c.itemContent.link : c.itemContent.default;
  const titleClasses = menuListItem ? c.title.menuListItem : strongTitle === true || autoStrongTitle ? c.title.strong : c.title.default;
  if (groupTitle) {
    return /*#__PURE__*/_react.default.createElement(Component, {
      className: (0, _cls.cls)(c.groupTitle, className)
    }, title, children);
  }
  return /*#__PURE__*/_react.default.createElement(Component, _extends({
    ref: elRef,
    className: c.base
  }, attrs), /*#__PURE__*/_react.default.createElement(ItemContentComponent, _extends({
    ref: rippleElRef,
    className: itemContentClasses
  }, linkPropsComputed), media && /*#__PURE__*/_react.default.createElement("div", {
    className: c.media
  }, media), /*#__PURE__*/_react.default.createElement("div", {
    className: c.inner
  }, header && /*#__PURE__*/_react.default.createElement("div", {
    className: c.header
  }, header), (title || after) && /*#__PURE__*/_react.default.createElement("div", {
    className: c.titleWrap
  }, title && /*#__PURE__*/_react.default.createElement("div", {
    className: titleClasses
  }, title), after && /*#__PURE__*/_react.default.createElement("div", {
    className: c.after
  }, after), isLink && hasChevron && !menuListItem && (chevronIcon || /*#__PURE__*/_react.default.createElement(_ChevronIcon.default, {
    className: c.chevron
  }))), subtitle && /*#__PURE__*/_react.default.createElement("div", {
    className: c.subtitle
  }, subtitle), text && /*#__PURE__*/_react.default.createElement("div", {
    className: c.text
  }, text), footer && /*#__PURE__*/_react.default.createElement("div", {
    className: c.footer
  }, footer), innerChildren), contentChildren), children);
});
ListItem.displayName = 'ListItem';
var _default = exports.default = ListItem;
