// package/svelte/components/ListButton.svelte
<script>
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useTouchRipple } from '../shared/use-touch-ripple.js';
  import { ListButtonClasses } from '../../shared/esm/classes/ListButtonClasses.js';
  import { ListButtonColors } from '../../shared/esm/colors/ListButtonColors.js';
  import { useTheme } from '../shared/use-theme.js';
  import { getReactiveContext } from '../shared/get-reactive-context.js';

  let className = undefined;
  export { className as class };
  let colorsProp = undefined;
  export { colorsProp as colors };
  export let ios = undefined;
  export let material = undefined;

  // Link props
  export let href = undefined;
  export let target = undefined;

  // Button props
  export let type = undefined;
  export let value = undefined;

  export let linkProps = {};

  export let touchRipple = true;

  export let linkComponent = 'a';

  export let onClick

  let ListDividersContext = getReactiveContext(
    'ListDividersContext',
    (value) => {
      ListDividersContext = value || {};
    }
  ) || { value: false };

  const rippleEl = { current: null };

  let theme;
  theme = useTheme({ ios, material }, (v) => (theme = v));

  $: useTouchRipple(rippleEl, touchRipple);

  const dark = useDarkClasses();

  $: colors = ListButtonColors(colorsProp, dark);

  $: c = useThemeClasses(
    { ios, material },
    ListButtonClasses(
      { dividers: ListDividersContext.value },
      colors,
      className,
      theme
    ),
    className,
    (v) => (c = v)
  );

  $: isLink = !!href || href === '';
  $: hrefComputed =
    !isLink || href === true || href === false ? undefined : href || '';
  $: buttonAttrs = { href: hrefComputed, target, type, value, ...linkProps };

  const ButtonComponent = isLink ? linkComponent : 'button';
</script>

<li class={c.base} {...$$restProps}>
  {#if typeof ButtonComponent === 'string'}
    <!-- svelte-ignore a11y-missing-attribute -->
    <svelte:element
      this={ButtonComponent}
      bind:this={rippleEl.current}
      class={c.button}
      {...buttonAttrs}
      on:click={onClick}
    >
      <slot />
    </svelte:element>
  {:else}
    <svelte:component
      this={ButtonComponent}
      bind:this={rippleEl.current}
      class={c.button}
      {...buttonAttrs}
      on:click={onClick}
    >
      <slot />
    </svelte:component>
  {/if}
</li>

// package/react/esm/components/ListButton.js
function _extends() { _extends = Object.assign ? Object.assign.bind() : function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; }; return _extends.apply(this, arguments); }
import React, { useRef, forwardRef, useImperativeHandle } from 'react';
import { useTheme } from '../shared/use-theme.js';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import { useDarkClasses } from '../shared/use-dark-classes.js';
import { useTouchRipple } from '../shared/use-touch-ripple.js';
import { ListButtonClasses } from '../../../shared/esm/classes/ListButtonClasses.js';
import { ListButtonColors } from '../../../shared/esm/colors/ListButtonColors.js';
import { useListDividers } from '../shared/use-list-dividers.js';
const ListButton = /*#__PURE__*/forwardRef((props, ref) => {
  const {
    component = 'li',
    className,
    colors: colorsProp,
    // Link props
    href,
    target,
    // Button props
    type,
    value,
    linkComponent = 'a',
    linkProps = {},
    ios,
    material,
    touchRipple = true,
    // Children
    children,
    // Rest
    ...rest
  } = props;
  const elRef = useRef(null);
  const rippleElRef = useRef(null);
  const dividers = useListDividers();
  useImperativeHandle(ref, () => ({
    el: elRef.current
  }));
  const Component = component;
  const attrs = {
    ...rest
  };
  const theme = useTheme({
    ios,
    material
  });
  const themeClasses = useThemeClasses({
    ios,
    material
  });
  useTouchRipple(rippleElRef, theme === 'material' && touchRipple);
  const dark = useDarkClasses();
  const colors = ListButtonColors(colorsProp, dark);
  const c = themeClasses(ListButtonClasses({
    ...props,
    dividers
  }, colors, className, theme), className);
  const isLink = !!href || href === '';
  const hrefComputed = !isLink || href === true || href === false ? undefined : href || '';
  const buttonAttrs = {
    href: hrefComputed,
    target,
    type,
    value,
    ...linkProps
  };
  const ButtonComponent = isLink ? linkComponent : 'button';
  return /*#__PURE__*/React.createElement(Component, _extends({
    ref: elRef,
    className: c.base
  }, attrs), /*#__PURE__*/React.createElement(ButtonComponent, _extends({
    ref: rippleElRef,
    className: c.button
  }, buttonAttrs), children));
});
ListButton.displayName = 'ListButton';
export default ListButton;
