// package/vue/components/Messagebar.vue
<template>
  <component :is="component" :id="id" ref="elRef" :class="c.base">
    <k-toolbar :outline="outline" :colors="colors">
      <div v-if="slots.left" :class="c.left"><slot name="left" /></div>
      <div :class="c.messagebarArea">
        <textarea
          id="textareaId"
          ref="areaElRef"
          type="textarea"
          :class="c.messagebarInput"
          :placeholder="placeholder"
          :name="name"
          :value="value"
          :disabled="disabled"
          :size="size"
          @input="onInput"
          @change="onChange"
          @focus="onFocusInternal"
        />
      </div>
      <div v-if="slots.right" :class="c.right"><slot name="right" /></div>
    </k-toolbar>
  </component>
</template>
<script>
  import { ref, computed } from 'vue';
  import { MessagebarClasses } from '../../shared/esm/classes/MessagebarClasses.js';
  import { MessagebarColors } from '../../shared/esm/colors/MessagebarColors.js';
  import { useDarkClasses } from '../shared/use-dark-classes.js';
  import { useThemeClasses } from '../shared/use-theme-classes.js';
  import kToolbar from './Toolbar.vue';

  export default {
    name: 'k-messagebar',
    components: {
      kToolbar,
    },
    props: {
      component: {
        type: String,
        default: 'div',
      },
      colors: {
        type: Object,
      },
      ios: {
        type: Boolean,
        default: undefined,
      },
      material: {
        type: Boolean,
        default: undefined,
      },
      id: String,
      name: { type: String, default: undefined },
      value: { type: [Number, String], default: undefined },
      placeholder: { type: String, defaullt: 'Message' },
      outline: { type: Boolean, default: false },
      rightClass: { type: String, default: '' },
      leftClass: { type: String, default: '' },
      disabled: { type: Boolean, default: undefined },
      textareaId: String,
      size: { type: [Number, String], default: undefined },
    },
    emits: ['change', 'input', 'focus'],
    setup(props, ctx) {
      const elRef = ref(null);
      const areaElRef = ref(null);
      const isFocused = ref(false);

      const colors = computed(() =>
        MessagebarColors(props.colors || {}, useDarkClasses)
      );

      const onFocusInternal = (e) => {
        isFocused.value = true;
        ctx.emit('focus', e);
      };

      const c = useThemeClasses(props, () =>
        MessagebarClasses(
          {
            ...props,
          },
          colors.value,
          { isFocused }
        )
      );

      const onChange = (e) => {
        ctx.emit('change', e);
      };

      const onInput = (e) => {
        ctx.emit('input', e);
      };

      return {
        elRef,
        areaElRef,
        c,
        onChange,
        onInput,
        onFocusInternal,
        slots: ctx.slots,
      };
    },
  };
</script>

// package/react/esm/components/Messagebar.js
function _extends() { _extends = Object.assign ? Object.assign.bind() : function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; }; return _extends.apply(this, arguments); }
import React, { forwardRef, useRef, useImperativeHandle, useState } from 'react';
import { useThemeClasses } from '../shared/use-theme-classes.js';
import { useDarkClasses } from '../shared/use-dark-classes.js';
import { MessagebarClasses } from '../../../shared/esm/classes/MessagebarClasses.js';
import { MessagebarColors } from '../../../shared/esm/colors/MessagebarColors.js';

// import Link from './Link.js';
import Toolbar from './Toolbar.js';
const Messagebar = /*#__PURE__*/forwardRef((props, ref) => {
  const {
    component = 'div',
    className,
    colors: colorsProp,
    id,
    style,
    name,
    placeholder = 'Message',
    value,
    outline = false,
    // eslint-disable-next-line
    leftClassName = '',
    // eslint-disable-next-line
    rightClassName = '',
    textareaId,
    disabled,
    size,
    left,
    right,
    ios,
    material,
    onInput,
    onChange,
    onFocus,
    children,
    ...rest
  } = props;
  const elRef = useRef(null);
  const areaElRef = useRef(null);
  useImperativeHandle(ref, () => ({
    el: elRef.current,
    areaElRef: areaElRef.current
  }));
  const [isFocused, setIsFocused] = useState(false);
  const themeClasses = useThemeClasses({
    ios,
    material
  });
  const dark = useDarkClasses();
  const colors = MessagebarColors(colorsProp, dark);
  const onFocusInternal = e => {
    setIsFocused(true);
    if (onFocus) onFocus(e);
  };
  const c = themeClasses(MessagebarClasses({
    ...props
  }, colors, {
    isFocused
  }));
  const Component = component;
  const attrs = {
    ...rest
  };
  return /*#__PURE__*/React.createElement(Component, _extends({
    ref: elRef,
    id: id,
    style: style,
    className: c.base
  }, attrs), /*#__PURE__*/React.createElement(Toolbar, {
    colors: colors,
    outline: outline
  }, left && /*#__PURE__*/React.createElement("div", {
    className: c.left
  }, left), /*#__PURE__*/React.createElement("div", {
    className: c.messagebarArea
  }, /*#__PURE__*/React.createElement("textarea", {
    id: textareaId,
    ref: areaElRef,
    type: "textarea",
    className: c.messagebarInput,
    placeholder: placeholder,
    name: name,
    size: size,
    disabled: disabled,
    onInput: onInput,
    onChange: onChange,
    onFocus: onFocusInternal,
    value: value
  })), right && /*#__PURE__*/React.createElement("div", {
    className: c.right
  }, right)));
});
Messagebar.displayName = 'Messagebar';
export default Messagebar;
